FROM node:20-alpine3.16 AS builder
WORKDIR /app
COPY package*.json ./
COPY tsconfig.*json ./
COPY src src 
RUN  npm install && npm run build

FROM node:20-alpine3.16 AS production
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev --ignore-scripts
COPY --from=builder /app/dist/ dist/
