name: Node.js CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Build latest
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml build

      - name: Provide doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_REGISTRY_TOKEN }}

      - name: Login to Digital Ocean Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push to Digital Ocean Registry
        run: docker push registry.digitalocean.com/straebe/node-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          script: |
            cd /var/www/html/straebe
            git pull origin master
            make prod-api
